name: modify_png_metadata
description: Sample for how to modify png metadata in Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path: ^1.9.0

  # Image
  path_provider: ^2.0.14 # for temp directory
  image_picker: ^1.1.1
  png_chunks_encode: ^1.0.0
  png_chunks_extract: ^1.0.2
  image_gallery_saver: ^2.0.3
  native_exif: ^0.5.0

  # Provider Pattern
  provider: ^6.0.5

  # Local DB
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0

  # Dependency Injection
  get_it: ^7.7.0

  # Localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
flutter_intl:
  enabled: true